###User methods-------------------------------------------------------------------------------------------------------

### saveUser
POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

{
  "name": "Chuck Norris",
  "email" : "chucknorris1@gmail.com"
}

### saveUser
POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

{
  "name": "Chuck Norris",
  "email" : "chucknorris2@gmail.com"
}

### saveUser
POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

{
  "name": "Chuck Norris",
  "email" : "chucknorris3@gmail.com"
}

### findAllUsers
GET http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

### findUserById
GET http://localhost:8080/api/users/1
Content-Type: application/json
Accept: application/json

### updateUser
PUT http://localhost:8080/api/users/1?loggedInUserId=1
Content-Type: application/json
Accept: application/json

{
  "name": "Chuck Norris",
  "email" : "gmail@chucknorris.com"
}

### findAllUsers
GET http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

### updateUser rossz jogosultsággal - NoAuthorityForActionException
PUT http://localhost:8080/api/users/1?loggedInUserId=2
Content-Type: application/json
Accept: application/json

{
  "name": "Chuck Norris",
  "email" : "gmail2@chucknorris.com"
}

### findAllUsers
GET http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

### deleteUser --- TODO minden esetre
DELETE http://localhost:8080/api/users/2?loggedInUserId=2&deleteRecipes=false
Content-Type: application/json
Accept: application/json

### deleteUser --- TODO minden esetre
DELETE http://localhost:8080/api/users/1?loggedInUserId=1&deleteRecipes=false
Content-Type: application/json
Accept: application/json

### findAllUsers
GET http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

### deleteUser rossz jogosultsággal - NoAuthorityForActionException
DELETE http://localhost:8080/api/users/3?loggedInUserId=1
Content-Type: application/json
Accept: application/json

### findAllUsers
GET http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

###Recipe methods-----------------------------------------------------------------------------------------------------

###  saveRecipe
POST http://localhost:8080/api/recipes?userId=1
Content-Type: application/json
Accept: application/json

{
  "preparation": "Szóval ez ide, azt meg oda, majd összekevered, megsütöd és kész.",
  "note" : "Néha amaz is kell bele. Néha."
}

###  saveRecipe
POST http://localhost:8080/api/recipes?userId=1
Content-Type: application/json
Accept: application/json

{
  "preparation": "Szóval ez ide, azt meg oda, majd összekevered, megsütöd és kész.",
  "note" : "Néha amaz is kell bele. Néha."
}

###  saveRecipe
POST http://localhost:8080/api/recipes?userId=1
Content-Type: application/json
Accept: application/json

{
  "preparation": "Szóval ez ide, azt meg oda, majd összekevered, megsütöd és kész.",
  "note" : "Néha amaz is kell bele. Néha."
}

###  saveRecipe
POST http://localhost:8080/api/recipes?userId=2
Content-Type: application/json
Accept: application/json

{
  "preparation": "Szóval ez ide, azt meg oda, majd összekevered, megsütöd és kész.",
  "note" : "Néha amaz is kell bele. Néha."
}

###  saveRecipe
POST http://localhost:8080/api/recipes?userId=3
Content-Type: application/json
Accept: application/json

{
  "preparation": "Szóval ez ide, azt meg oda, majd összekevered, megsütöd és kész.",
  "note" : "Néha amaz is kell bele. Néha."
}

### findAllRecipes
GET http://localhost:8080/api/recipes
Content-Type: application/json
Accept: application/json

### findRecipeById
GET http://localhost:8080/api/recipes/recipe/3
Content-Type: application/json
Accept: application/json

### findRandomRecipe
GET http://localhost:8080/api/recipes/recipe/random
Content-Type: application/json
Accept: application/json

### findRecipesByUser
GET http://localhost:8080/api/recipes/user/1
Content-Type: application/json
Accept: application/json

### updateRecipe
PUT http://localhost:8080/api/recipes/1?userId=1
Content-Type: application/json
Accept: application/json

{
  "preparation": "Ez pedig így meg úgy kell elkészíteni, jó étvágyat hozzá!",
  "note" : "Érdemes belőle 2 adagot készíteni, hogy a későn érkezőknek is jusson."
}

### findAllRecipes
GET http://localhost:8080/api/recipes
Content-Type: application/json
Accept: application/json

### updateRecipe rossz jogosultsággal - NoAuthorityForActionException
PUT http://localhost:8080/api/recipes/2?userId=2
Content-Type: application/json
Accept: application/json

{
  "preparation": "Ez pedig így meg úgy kell elkészíteni, jó étvágyat hozzá!",
  "note" : "Érdemes belőle 2 adagot készíteni, hogy a későn érkezőknek is jusson."
}

### findAllRecipes
GET http://localhost:8080/api/recipes
Content-Type: application/json
Accept: application/json

### deleteRecipe
DELETE http://localhost:8080/api/recipes/2?userId=1
Content-Type: application/json
Accept: application/json

### findAllRecipes
GET http://localhost:8080/api/recipes
Content-Type: application/json
Accept: application/json

### deleteRecipe rossz jogosultsággal - NoAuthorityForActionException
DELETE http://localhost:8080/api/recipes/1?userId=2
Content-Type: application/json
Accept: application/json

### findAllRecipes
GET http://localhost:8080/api/recipes
Content-Type: application/json
Accept: application/json

###Rating methods------------------------------------------------------------------------------------------------------

###  saveRating
POST http://localhost:8080/api/users/1/ratings/1
Content-Type: application/json
Accept: application/json

{
  "fingers": 8
}

###  saveRating - módosítás
POST http://localhost:8080/api/users/1/ratings/1
Content-Type: application/json
Accept: application/json

{
  "fingers": 6
}

###  saveRating
POST http://localhost:8080/api/users/3/ratings/1
Content-Type: application/json
Accept: application/json

{
  "fingers": 7
}

###  saveRating
POST http://localhost:8080/api/users/3/ratings/3
Content-Type: application/json
Accept: application/json

{
  "fingers": 9
}

###  findRatingByUserAndRecipe
GET http://localhost:8080/api/users/3/ratings/1
Content-Type: application/json
Accept: application/json

###  findAllRatingsByUser
GET http://localhost:8080/api/users/3/ratings/
Content-Type: application/json
Accept: application/json

###  findAllRatingsByUser
GET http://localhost:8080/api/users/1/ratings/
Content-Type: application/json
Accept: application/json

###  deleteRating
DELETE http://localhost:8080/api/users/1/ratings/1
Content-Type: application/json
Accept: application/json

###  findAllRatingsByUser
GET http://localhost:8080/api/users/1/ratings/
Content-Type: application/json
Accept: application/json
